### ISSUE TITLE
Radix sort test fails

### ISSUE THREAD

**Issue by arcman7** [kishimisu/WebGPU-Radix-Sort#2] opened 2024-06-05 03:21 UTC
I cloned the repo and ran the radix sort test from index.js:

```
// example/index.js : line 18
async function main_demo() {
  // Init WebGPU
  const adapter = await navigator.gpu?.requestAdapter();
  const device = await adapter?.requestDevice();
  if (!device) throw new Error("Could not create WebGPU device");

  // Test Prefix Sum Kernel
  if (false) {
    return test_prefix_sum(device);
  }

  // Test Radix Sort Kernel
  if (true) {
    return test_radix_sort(device);
  }
  
//  ...
// rest of file

```

But I get see error message in the console that is printed whenever the expected elements from the test don't match the results of the mapped sorting buffer.

Are you able to repo this as well? 

I ran the same test on your page:
https://kishimisu.github.io/WebGPU-Radix-Sort/

By putting a debugger stopping point at:
https://github.com/kishimisu/WebGPU-Radix-Sort/blob/df8ef153c5718bb6a9069f3e9bf4d2499ec1071e/example/index.js#L38
And then ran the radix sort test from there; I was able to repo the error message.

**Comment by kishimisu** [comment] 2024-06-05 20:03
Thank you for pointing this out!

The code you sent is from a previous version of `index.js`, could you confirm that you're having the same issue with the latest version?
I made sure that all tests were working on my machine before publishing, so I unfortunately cannot reproduce.

It could also help if you sent the entire console logs to understand at what step of the test it failed.

**Comment by kishimisu** [comment] 2024-06-05 21:16
In the case you're still having this issue in the latest version, can you see if the latest PR fixes the failing tests ?

**Comment by arcman7** [comment] 2024-06-06 21:25
> In the case you're still having this issue in the latest version, can you see if the latest PR fixes the failing tests ?

Okay, testing now

**Comment by arcman7** [comment] 2024-06-06 21:54
I clone your branch locally, ran `npm run build` from terminal then opened up index.html using vs-code live server extension which just hosts index.html on a local host server.

Here's a screen shot of a new shader error I'm seeing (this doesn't happen on main branch):
![image](https://github.com/kishimisu/WebGPU-Radix-Sort/assets/9598327/db940500-054f-4946-9e95-0ed9a1056eea)

**Comment by kishimisu** [comment] 2024-06-06 22:01
I apologize for the oversight, forgot to change a `let` to `var` in the wgsl code. I've made a new commit that fixes this.

**Comment by arcman7** [comment] 2024-06-06 22:38
Here's my chrome version and build:
```
Chrome is up to date
Version 125.0.6422.142 (Official Build) (64-bit)
```

I seriously doubt this has much to do with the chrome version though, re-assigning a let variable in wgsl seems like some sort of parsing issue. Maybe when you run the bundle command npm script, there's something parsing the wgsl strings in the javascript file and replacing every instance of "var" with "let".


I changed the source file shader code to correctly use var in the two place this occurs in radix-sort-esm.js and the shader executes and I go back to only seeing wrong sort values error.

**Comment by kishimisu** [comment] 2024-06-06 22:41
Yes I doubt this is due to Chrome. What's your GPU?
Also does it fail on the very first test, or after a few have passed?

**Comment by arcman7** [comment] 2024-06-06 23:25
Windows 10
NVIDIA GeForce GTX 1070

And yes two tests passed then maybe it was the third test that failed, I'll check again

**Comment by arcman7** [comment] 2024-06-06 23:48
Wait now, it also fails at exp = 3, so it failed at the second iteration

**Comment by kishimisu** [comment] 2024-06-07 00:00
Thank you for the feedback.
This behavior looks like a synchronization issue between threads, but this was what I tried to fix in my first commit.

I've just pushed another commit that prevent any out-of-bounds access for arrays in shaders. 
Could you test if it changes anything?

**Comment by arcman7** [comment] 2024-06-07 00:32
This seems to have fixed the issue... the full set of tests are still running but not one has failed so far

**Comment by arcman7** [comment] 2024-06-07 00:37
When I use the optimization "avoid bank conflicts" I see the following shader error:
![image](https://github.com/kishimisu/WebGPU-Radix-Sort/assets/9598327/99209b5d-c78e-4785-b4e5-e9c6f2865021)

But other wise the other optimization modes run fine, but I don't know if the results are correct or not

**Comment by kishimisu** [comment] 2024-06-07 00:41
Wonderful!

Yes I did not implement the fix for the optimization shaders yet, these fails are expected.
I will push a new version with the correct changes

**Comment by kishimisu** [comment] 2024-06-07 00:58
Would it be possible for you to tell me if the tests still passes when setting `avoid_bank_conflicts` to `false` and removing the following line in `src/shaders/prefix_sum.js (line 45)` ?

```
45    workgroupBarrier();```

**Comment by arcman7** [comment] 2024-06-07 01:19
Yeah looks good:

```
   const check_order = false
   const local_shuffle = false
   const avoid_bank_conflicts = false
```
![image](https://github.com/kishimisu/WebGPU-Radix-Sort/assets/9598327/0eab8dc0-82d8-41cc-bdbd-68d11dcc04e9)


```
   const check_order = true
   const local_shuffle = true
   const avoid_bank_conflicts = false
```
![image](https://github.com/kishimisu/WebGPU-Radix-Sort/assets/9598327/ef05f294-2015-4509-92ce-8968570a648b)

I need to work for a bit now, so I'll check back tomorrow

**Comment by kishimisu** [comment] 2024-06-07 02:08
Thank you for testing!

These new fixes are now [merged into main](https://github.com/kishimisu/WebGPU-Radix-Sort/commit/9797fcb90a8afbc432da09d9b879d0ef30072a74) and the npm package is updated to `1.0.7`.

**Closed by kishimisu** 2024-06-07 02:08 UTC

**Comment by arcman7** [comment] 2024-06-07 20:39
This is fantastic! Looking forward to using this!!
